### ISSUE TITLE
[IDEA] Compatibility with Theme and Palette

### ISSUE THREAD

**Issue by kookma** [oeyoews/tiddlywiki-codemirror6#101]
### Describe the bug

These are just suggestions, ignore if irrelevant

1. Move CodeMiror settings under Settings in $:/ControlPanel
2. Lets follow the theme and palette (the current design mostly follows this)
3. Remove the shadows and use a flat/plain page for settings, now it has shadows and 3D effects

I myself like flat/uncluttered simple design.

**Comment by kookma** [comment]
Also for icons, wherever is possible, you may use https://github.com/morosanuae/tw-icons or other resources, but I would recommend following the core convention. That means use square icons with 22pt in width.

I understand for dropdown and triggers you may want smaller icons.

**Comment by oeyoews** [comment]
Regarding the appearance, I actually haven't done anything about it. I'm waiting for TW's official method of unified processing of dark and light (although I have my own method), but it seems there's still not much hope now.

**Comment by oeyoews** [comment]
https://icon-sets.iconify.design/ Currently all icons come from here and are stored in the dictionary tiddler $:/plugins/oeyoews/tiddlywiki-codemirror-6/icon-dict. I haven't noticed the details of these styles yet. Should be easier to handle

**Comment by kookma** [comment]
Thank you for clarification! I close this ticket as it is a matter of taste!
Thank you for all your efforts. I am sure this plugin will get a lot of attention
as it makes note taking in TW much more pleasant.
