### ISSUE TITLE
[IDEA] Add ChangeLog

### ISSUE THREAD

**Issue by kookma** [oeyoews/tiddlywiki-codemirror6#104]
As the CodeMirror6 plugin is under continuous development. I would recommend adding a ChangeLog tiddler
like: https://kookma.github.io/TW-Utility/#ChangeLog

This way one can realizes what are the changes from version to version!

**Comment by oeyoews** [comment]
I admit I got a bit lazy. I hope the next version brings new features too. Completing the codemirror6 lang-tiddlywiki to achieve proper syntax highlighting for TiddlyWiki is an interesting goal. Lezer can be quite challenging.

**Comment by kookma** [comment]
Thank you for all your efforts.

**Comment by oeyoews** [comment]
1419a91ffa6a103ef1abe1a49a6f04e28f2e7ec6
