### ISSUE TITLE
translate翻译功能有实装吗？

### ISSUE THREAD

**Issue by king0billy** [oeyoews/tiddlywiki-codemirror6#79]
$:/plugins/oeyoews/tiddlywiki-codemirror-6/ui/EditorToolbar/translate

**Comment by linonetwo** [comment]
用最新的 lingo 过程来翻译吧 https://github.com/Jermolene/TiddlyWiki5/pull/7821

**Comment by oeyoews** [comment]
> $:/插件/oeyoews/tiddlywiki-codemirror-6/ui/EditorToolbar/translate

这个只是codemirror内置的一个功能，我当时测试了，似乎并没有什么用
