### ISSUE TITLE
win10拼音输入法+回车后立即点保存, 会丢失键入的英文字符串

### ISSUE THREAD

**Issue by Hydrowood0** [oeyoews/tiddlywiki-codemirror6#84]
https://4bug-report.tiddlyhost.com/ 您可以在线复现我的bug

https://github.com/oeyoews/tiddlywiki-codemirror6/assets/172965706/ddcb8c6f-ae5b-4802-b20e-77bd8f20a5c5

**Comment by oeyoews** [comment]
![image](https://github.com/oeyoews/tiddlywiki-codemirror6/assets/72405338/739383b0-d1b4-4434-abc2-baaa91aefaa7)
 
1. https://github.com/replit/codemirror-vim/issues/156#issuecomment-1886085825 你在tiddlyhost 上的网页有这个问题, 这个在tiddlyhost 上的bug暂时修不了

![image](https://github.com/oeyoews/tiddlywiki-codemirror6/assets/72405338/1f77f732-42cd-40d9-9dda-bb3a5eafb3c5)
2. 这个功能暂时不要开, 有性能问题, 你可能已经感觉到了, 打字会有一定的延迟,不够流畅.
3. 上面视频中的问题无法复现.  https://tiddlywiki-codemirror6.vercel.app/#%24%3A%2Fplugins%2Foeyoews%2Ftiddlywiki-codemirror-6 如果可以访问这个地址, 最好直接在这里录屏复现, 排除其他因素导致的bug

**Comment by Hydrowood0** [comment]
现在我重新上传了无shadow版本的snapshot.htm, 你再试试. 同样的拼音+回车操作在tiddlyhost和nodejs上效果不同.


https://github.com/oeyoews/tiddlywiki-codemirror6/assets/172965706/5a9531f0-9f53-45e1-8164-299e6cbb8c69

**Comment by Hydrowood0** [comment]
> 现在我重新上传了无shadow版本的snapshot.htm, 你再试试. 同样的拼音+回车操作在tiddlyhost和nodejs上效果不同.

我怀疑是同样的原理, 拼音状态下导致键入第二个`[`后, 没有任何反应, 没有弹出任何预览提示/窗口

**Comment by oeyoews** [comment]
> 现在我重新上传了无shadow版本的snapshot.htm, 你再试试. 同样的拼音+回车操作在tiddlyhost和nodejs上效果不同.
> 
>  2024-06-21.02-07-05.mp4

https://github.com/replit/codemirror-vim/issues/156#issuecomment-1886085825

**Comment by Hydrowood0** [comment]
> [replit/codemirror-vim#156 (comment)](https://github.com/replit/codemirror-vim/issues/156#issuecomment-1886085825)

我没看懂你想说什么, 我从来都没开vim模式, 所以不是这个设置的原因
现在我只知道把设置调回和https://tiddlywiki-codemirror6.vercel.app/#%24%3A%2Fplugins%2Foeyoews%2Ftiddlywiki-codemirror-6一样的默认就不会出现我报告的bug.

**Comment by oeyoews** [comment]
已复现, codemirror最近版本升级的问题, 修复中

**Comment by oeyoews** [comment]
上游codemirror/view 6.28.2 有问题, 插件已降级修复

**Comment by Hydrowood0** [comment]
你确认已修复吗, 我安装了你推送的最新版还是如这个issue题目一模一样的bug.
PS: 有空我再打包一份安装了最新的codemirror6的插件上传到tiddlyhost

**Comment by oeyoews** [comment]
6.28.2 似乎也有一个compositonstart 的问题， codemirror6 lib暂时不升级了(暂时没时间精力处理上游问题了）
